runtime: custom
env: flex

# Metabase does not support horizontal scaling
#   https://github.com/metabase/metabase/issues/2754
#   https://cloud.google.com/appengine/docs/flexible/java/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1

resources:
  memory_gb: 4

env_variables:
  MB_JETTY_PORT: 8080
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: 5432
  MB_DB_USER: username_database
  MB_DB_PASS: password_database
  MB_DB_HOST: 127.0.0.1
  CLOUD_SQL_INSTANCE: connection_url_instance_sql
  